name: 5.X - Wazuh - Legacy Unit tests

on:
  workflow_dispatch:
    inputs:
      base_branch:
        description: 'Base branch'
        required: true
        default: 'main'
  pull_request:
    paths:
        - "src/**"
        - ".github/workflows/5_testunit_linux-win.yml"

jobs:
  Unit-Tests:
    strategy:
          fail-fast: false
          matrix:
              target: [agent, winagent, server]
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: "Install dependencies"
        uses: ./.github/actions/install_build_deps
        with:
          target: ${{ matrix.target }}
      - name: "Install a compatible CMake"
        uses: ./.github/actions/reinstall_cmake
      - name: "Install gcc 14.3"
        run: |
          echo "Download GCC 14.3 package"
          cd /tmp
          for i in {1..3}; do
            if wget --timeout=30 --tries=3 https://packages.wazuh.com/utils/gcc/gcc_14.3-1_amd64.deb; then
              break
            fi
            echo "Download attempt $i failed, retrying..."
            sleep 2
          done

          echo "Verify download succeeded"
          if [ ! -f gcc_14.3-1_amd64.deb ]; then
            echo "Failed to download GCC package after 3 attempts"
            exit 1
          fi

          sudo dpkg -i gcc_14.3-1_amd64.deb || {
            echo "Package installation failed, trying to fix dependencies"
            sudo apt-get update && sudo apt-get install -f -y
            sudo dpkg -i gcc_14.3-1_amd64.deb
          }

          # Create symlinks with backup of original
          sudo mv /usr/bin/gcc /usr/bin/gcc.bak 2>/dev/null || true
          sudo mv /usr/bin/g++ /usr/bin/g++.bak 2>/dev/null || true
          sudo mv /usr/bin/c++ /usr/bin/c++.bak 2>/dev/null || true
          sudo ln -sf /opt/gcc-14/bin/gcc /usr/bin/gcc
          sudo ln -sf /opt/gcc-14/bin/g++ /usr/bin/g++
          sudo ln -sf /opt/gcc-14/bin/g++ /usr/bin/c++

          # Verify compiler works
          gcc --version
          g++ --version
      - name: "Build wazuh"
        uses: ./.github/actions/build_test_flags
        with:
          target: ${{ matrix.target }}
      - name: "Build wazuh legacy unit tests"
        uses: ./.github/actions/legacy_unit_tests_build
        with:
          target: ${{ matrix.target }}
      - name: "Run wazuh legacy unit tests"
        uses: ./.github/actions/legacy_unit_tests_run
        with:
          target: ${{ matrix.target }}
