name: 5.X - Engine - Unit tests

on:
  # Triggers the workflow on pull request but only changes in the src/engine/ directory.
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    paths:
      - 'src/engine/**'

# Ensures only one instance of this workflow is running per PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  BUILD_DIR: ${{github.workspace}}/src/build
  ENGINE_CMAKE: src/engine/CMakeLists.txt

jobs:
  build:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install CMake
        uses: ./.github/actions/reinstall_cmake

      - name: Force ENGINE_ENABLE_ASAN=ON in CMakeLists

        run: |
          file="${ENGINE_CMAKE}"
          grep -qE 'option\(\s*ENGINE_ENABLE_ASAN\b' "$file" || {
            echo "ERROR: ENGINE_ENABLE_ASAN option not found in ${file}"; exit 1; }

          sed -i -E 's/^(option\(\s*ENGINE_ENABLE_ASAN\b[^)]*\b)OFF(\b[^)]*\))/\1ON\2/' "$file" || {
            echo "ERROR: sed failed setting ENGINE_ENABLE_ASAN=ON"; exit 1; }

          grep -nE 'option\(\s*ENGINE_ENABLE_ASAN\b.*\bON\b' "$file" || {
            echo "ERROR: ENGINE_ENABLE_ASAN not set to ON in ${file}"; exit 1; }

      - name: Build Wazuh server
        run: |
          make deps -C src TARGET=server -j$(nproc)
          make -C src TARGET=server ENGINE_TEST=y -j$(nproc)

      - name: Unit Test
        # Run unit tests using CTest
        working-directory: ${{env.BUILD_DIR}}/engine
        env:
          ASAN_OPTIONS: malloc_context_size=8:print_stats=0:fast_unwind_on_malloc=1:log_path=${{ runner.temp }}/asan
          LSAN_OPTIONS: report_objects=0:log_path=${{ runner.temp }}/asan
        run: MALLOC_CHECK_=2 ctest -T test --output-on-failure -j$(nproc)

      - name: Upload ASAN/LSAN logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: sanitizer-logs
          path: |
            ${{ runner.temp }}/asan*
          if-no-files-found: ignore
          retention-days: 7
